### ISSUE TITLE
Error on Psychedelicraft when joining server

### ISSUE THREAD

**Issue by thedeskinator** [MineLittlePony/Fabwork#3]
Hey, I get an error that says "failed to encode custom packet fabworks sychronize" whenever I try to join my server. The dev of psychedelicraft told me to make a report here. I am using fabric. My mods list is Architectury, Artifacts, Carryon, Cloth-Config, Collective, Cupboard, Fabric API, psychidelicraft, Structure Essentials, Trinkets, and Simple voice chat, on 1.21.1. Serverside, it says 

[15:23:24] [User Authenticator #1/INFO]: UUID of player miatafan95 is 975e5336-5cdd-4fe0-b904-694710c2c1a9
[15:23:24] [Netty Server IO #1/INFO]: Sending mod list to miatafan95[/192.168.1.62:50833]
[15:23:24] [Netty Server IO #1/ERROR]: Error sending packet clientbound/minecraft:custom_payload
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (fabwork:synchronize)
	at net.minecraft.class_9136.handler$zmn000$fabric-networking-api-v1$encode(class_9136.java:547) ~[server-intermediary.jar:?]
	at net.minecraft.class_9136.method_56426(class_9136.java:55) ~[server-intermediary.jar:?]
	at net.minecraft.class_9136.encode(class_9136.java:14) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:26) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:12) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535$2.write(class_2535.java:530) ~[server-intermediary.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:350) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10764(class_2535.java:343) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_52906(class_2535.java:325) ~[server-intermediary.jar:?]
	at net.minecraft.class_8609.method_52391(class_8609.java:152) ~[server-intermediary.jar:?]
	at net.minecraft.class_8609.method_14364(class_8609.java:143) ~[server-intermediary.jar:?]
	at com.sollace.fabwork.impl.FabworkServer$1.method_52376(FabworkServer.java:47) ~[fabwork-1.3.0+1.21-327ccf67d2e9d4c8.jar:?]
	at net.minecraft.class_8610.method_52412(class_8610.java:177) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.method_52406(class_8610.java:187) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.completeTask(class_8610.java:653) ~[server-intermediary.jar:?]
	at net.fabricmc.fabric.impl.recipe.ingredient.CustomIngredientSync.lambda$onInitialize$2(CustomIngredientSync.java:99) ~[fabric-recipe-api-v1-5.0.12+650897126a-1d260837d6711ee5.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerConfigurationNetworkAddon.receive(ServerConfigurationNetworkAddon.java:108) ~[fabric-networking-api-v1-4.2.2+60c3209b6a-6121c3e3ce9d90d0.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerConfigurationNetworkAddon.receive(ServerConfigurationNetworkAddon.java:42) ~[fabric-networking-api-v1-4.2.2+60c3209b6a-6121c3e3ce9d90d0.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:97) ~[fabric-networking-api-v1-4.2.2+60c3209b6a-6121c3e3ce9d90d0.jar:?]
	at net.minecraft.class_8609.handler$znh000$fabric-networking-api-v1$handleCustomPayloadReceivedAsync(class_8609.java:541) ~[server-intermediary.jar:?]
	at net.minecraft.class_8609.method_52392(class_8609.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_2817.method_12199(class_2817.java:36) ~[server-intermediary.jar:?]
	at net.minecraft.class_2817.method_11054(class_2817.java:15) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:208) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:193) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:69) ~[server-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) ~[netty-handler-4.1.97.Final.jar:?]
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164) ~[netty-handler-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassCastException: class com.sollace.fabwork.impl.ConsentMessage cannot be cast to class net.minecraft.class_8711 (com.sollace.fabwork.impl.ConsentMessage and net.minecraft.class_8711 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @59ec2012)
	at net.minecraft.class_9139$6.encode(class_9139.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.class_8710$1.method_56489(class_8710.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_8710$1.method_56490(class_8710.java:57) ~[server-intermediary.jar:?]
	at net.minecraft.class_8710$1.encode(class_8710.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$8.encode(class_9139.java:81) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$9.method_56442(class_9139.java:97) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$9.encode(class_9139.java:87) ~[server-intermediary.jar:?]
	at net.minecraft.class_9136.method_56426(class_9136.java:53) ~[server-intermediary.jar:?]
	... 81 more
[15:23:24] [Server thread/INFO]: com.mojang.authlib.GameProfile@4fbcb936[id=975e5336-5cdd-4fe0-b904-694710c2c1a9,name=miatafan95,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTcyNDM1NDU4ODkzNSwKICAicHJvZmlsZUlkIiA6ICI5NzVlNTMzNjVjZGQ0ZmUwYjkwNDY5NDcxMGMyYzFhOSIsCiAgInByb2ZpbGVOYW1lIiA6ICJtaWF0YWZhbjk1IiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2NkZGU2ZDU0MGNjMWFjMGZhYmU1MzU5MTgyNzlkY2VmNzcxZDU2NDFiNTA1YmFjMWQ2MmY5OGNlMjlkNzFmM2YiCiAgICB9LAogICAgIkNBUEUiIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzIzNDBjMGUwM2RkMjRhMTFiMTVhOGIzM2MyYTdlOWUzMmFiYjIwNTFiMjQ4MWQwYmE3ZGVmZDYzNWNhN2E5MzMiCiAgICB9CiAgfQp9, signature=gbN79aZ3em+ADWZmm/BITIiPWZImW1dNoBvyogVIKCtL3ej+zO3k8dDrU37LcsQmP7rk+I5Ifh0Slp6xwtU6yxLO9xCDbl7z6RG62nXLYsXRq+v10KSz/ZkHuPmpe0Ca3LWU+NbU1BCHEdHnt2YAWd1kIzOwe1R+f05/GtIJ3/jnMFPPZ1nnwKKCkRCdWY13mWZxiYWFbFTqMGo7xVLTGTVbYZTHiyEM1LI7LOiqIT7FuIZ6yTRN8CVfq8mq1odtSSPDzEqVE3wdW2LL3QOQp8ERxyHH+ufw/h8eMXt2APLEB4TD6LIHaDaBrAXU+1g9P7yKQGMwsj0r72Bh6C2StB27dXk2IN21SzVTgWajBXok77DiPex8rBW9B9wKToa28c2E6dPEkzsX8471Goy8HAR0mFwtsxcA8FNLGJfd4pTeH/qbSDw9O8NRjHiLhAVJLJfumiiWrQcCzcOSOyCzyH+ddsDzQypl9zC1wTgJ4IgFLCJSdEZk44GY+S3i3j3zjsG8mqbEwE7pSaVqYuetBxkaPzJA00drEhHKw4ty5af0EF3vrOrOR+AIyDa/IrWapjDPYjKbOlZdjfAjZBgyoFKPnx6Gh7dqRsCGoGTFd3+zkn0Kd/rzgORFFOeR3j+sV5cNjWRCRMNa47uO/Y3EFUcIC/Z4bgVXXsgLAU3ruQQ=]]}] lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (fabwork:synchronize)

Does anyone know what could be causing this issue? Thanks

**Comment by Sollace** [comment]
Thanks for the report!

Can you try adding this version to your mods folder on the server and see if it fixes your problem?

https://github.com/MineLittlePony/Fabwork/releases/tag/1.3.1-beta.1%2B1.21

**Comment by thedeskinator** [comment]
Hey, thanks for responding
It gives me a different error now, even when I remove all mods except for the fabwork version you gave me, fabric api, and psychedelicraft 
It says: failed to encode packet clientbound/minecraft:custom payload (Psychedelicraft update drug properties)
Serverside it just has the same message as what it says on the client

**Comment by Sollace** [comment]
Okay cool. It does at least sound like the first issue is resolved. I'll look into fixing the other one later tomorrow.

Thanks for your patience with this.

**Comment by thedeskinator** [comment]
no problem, thanks for the help

**Comment by SamBrimhall** [comment]
Adding that I'm experiencing the same issue posted above.

Here are my logs when trying to join the server after installing the suggested fix:

Client:
Client disconnected with reason: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (psychedelicraft:update_drug_properties)

Server:
[13:59:06] [Netty Server IO #2/ERROR]: Error sending packet clientbound/minecraft:custom_payload
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (psychedelicraft:update_drug_properties)
	at net.minecraft.class_9136.handler$zkd000$fabric-networking-api-v1$encode(class_9136.java:547) ~[server-intermediary.jar:?]
	at net.minecraft.class_9136.method_56426(class_9136.java:55) ~[server-intermediary.jar:?]
	at net.minecraft.class_9136.encode(class_9136.java:14) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:26) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:12) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535$2.write(class_2535.java:530) ~[server-intermediary.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:350) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_52917(class_2535.java:345) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.ClassCastException: class com.sollace.fabwork.api.packets.Payload cannot be cast to class net.minecraft.class_8711 (com.sollace.fabwork.api.packets.Payload and net.minecraft.class_8711 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4cf777e8)
	at net.minecraft.class_9139$6.encode(class_9139.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.class_8710$1.method_56489(class_8710.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_8710$1.method_56490(class_8710.java:57) ~[server-intermediary.jar:?]
	at net.minecraft.class_8710$1.encode(class_8710.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$8.encode(class_9139.java:81) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$9.method_56442(class_9139.java:97) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$9.encode(class_9139.java:87) ~[server-intermediary.jar:?]
	at net.minecraft.class_9136.method_56426(class_9136.java:53) ~[server-intermediary.jar:?]
	... 31 more

**Comment by Sollace** [comment]
> no problem, thanks for the help

Hey sorry for the wait. Here's another version that you can try. Hopefully this fixes all the issues.
If it works I will do a new release for both 1.21 and 1.20.5 (as I believe that version is affected)

https://github.com/MineLittlePony/Fabwork/releases/tag/1.3.1-beta.2%2B1.21

**Comment by Sollace** [comment]
https://github.com/MineLittlePony/Fabwork/releases/tag/1.3.1%2B1.21
